- name: Restart Apache for RedHat
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Restart Apache for Debian
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"                                            
