---
- name: Install required packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ca-certificates

- name: Update APT package cache
  ansible.builtin.yum:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.yum:
    name=nginx
    state=latest
