---
- name: Install Docker Compose
  become: yes
  become_user: root
  command: >
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
    chmod +x /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Copy Docker Compose file
  copy:
    src: "{{ docker_compose_path | default('/path/to/your/docker-compose.yml') }}"
    dest: "{{ docker_compose_path }}"

- name: Run Docker Compose
  command: "docker-compose -f {{ docker_compose_path }} up -d"
  become_user: "{{ docker_user | default('your_docker_user') }}"
  notify: restart docker service
